<<: *pysim_simulation
desired_apogee: 6432
rocket:
  <<: *simulated_rocket
  rasaero_lookup_file: "not asdf"
  C_d: 1
  C_d_s: 1
  length: 1
  dry_mass: 1
  radius: 1
  cm: !numpy/array [1, 0, 0]
motor:
  <<: *simulated_motor
  impulse: 1000
  motor_mass: 1000
  delay: 60
  motor_lookup_file: "asdasd"
  cm: !numpy/array [1, 0, 0]
simulated_body:
  <<: *simulated_body
  cm: !numpy/array [1, 0, 0]
  cp: !numpy/array [1, 0, 0]
meta:
  output_file: '../output/simulated_6dof.csv'
  monte_carlo_output_folder: '../output/monte_carlo'